#!/usr/bin/env bash
# Run before every push. A commit is local and recoverable; a push is neither.
#
# Every check reports whether it RAN, not just whether it found nothing. A check
# that errors on its own arguments and prints "clean" manufactures false
# confidence, which is worse than no check at all.
set -uo pipefail
cd "$(git rev-parse --show-toplevel)"

fail=0
ran=0

say()  { printf '%-38s %s\n' "$1" "$2"; }
scan() {
  desc="$1"; shift
  ran=$((ran + 1))
  out=$(git ls-files -z | grep -zv '^registry/issuers.yaml$' | xargs -0 grep -nIE -e "$@" 2>/dev/null)
  rc=$?
  if [ $rc -eq 2 ]; then
    say "$desc" "SCAN ERROR — not a pass"; fail=1
  elif [ $rc -eq 0 ]; then
    say "$desc" "FOUND:"; printf '%s\n' "$out" | sed 's/^/    /'; fail=1
  else
    say "$desc" "pass"
  fi
}

echo "── secrets ──"
scan "aws access key id"     '(AKIA|ASIA)[0-9A-Z]{16}'
scan "github token"          'gh[pousr]_[A-Za-z0-9]{20,}'
scan "private key block"     'BEGIN [A-Z ]*PRIVATE KEY'
scan "slack token"           'xox[abprs]-[A-Za-z0-9-]{10,}'
scan "generic assignment"    '(api[_-]?key|secret|passwd|password|token)[[:space:]]*[:=][[:space:]]*["'"'"'][^"'"'"']{12,}'
scan "production host"       '89\.167\.75\.180'

ran=$((ran + 1))
if git ls-files | grep -qE '(^|/)\.env($|\.)' ; then
  say "no .env tracked" "FOUND"; fail=1
else
  say "no .env tracked" "pass"
fi

echo
echo "── authorship ──"
ran=$((ran + 1))
unpushed=$(git log --format='%H' @{upstream}..HEAD 2>/dev/null || git log --format='%H' -10)
bad=0
for sha in $unpushed; do
  if git log -1 --format='%an <%ae>%n%B' "$sha" | grep -qiE 'co-authored|generated with|generated by|assisted by|claude|anthropic|copilot'; then
    say "commit ${sha:0:8}" "ATTRIBUTION FOUND"; bad=1
  fi
done
[ $bad -eq 0 ] && say "unpushed commit messages" "pass" || fail=1

echo
echo "── tree ──"
ran=$((ran + 1))
if [ -n "$(git status --porcelain)" ]; then
  say "working tree clean" "DIRTY — commit or stash first"
  git status --short | sed 's/^/    /'
  fail=1
else
  say "working tree clean" "pass"
fi

echo
echo "──────────────────────────────────────"
echo "checks run: $ran"
if [ $fail -eq 0 ]; then
  echo "PREFLIGHT PASS — every check executed and passed"
else
  echo "PREFLIGHT FAIL — do not push"
  exit 1
fi
