#!/usr/bin/env bash
# Run before every push. A commit is local and recoverable; a push is neither.
#
# Every check reports whether it RAN, not just whether it found nothing. A check
# that errors on its own arguments and prints "clean" manufactures false
# confidence, which is worse than no check at all.
set -uo pipefail
cd "$(git rev-parse --show-toplevel)"

fail=0
ran=0

say()  { printf '%-38s %s\n' "$1" "$2"; }
scan() {
  desc="$1"; shift
  ran=$((ran + 1))
  out=$(git ls-files -z | grep -zv '^registry/issuers.yaml$' | xargs -0 grep -nIE -e "$@" 2>/dev/null)
  rc=$?
  if [ $rc -eq 2 ]; then
    say "$desc" "SCAN ERROR — not a pass"; fail=1
  elif [ $rc -eq 0 ]; then
    say "$desc" "FOUND:"; printf '%s\n' "$out" | sed 's/^/    /'; fail=1
  else
    say "$desc" "pass"
  fi
}

echo "── secrets ──"
scan "aws access key id"     '(AKIA|ASIA)[0-9A-Z]{16}'
scan "github token"          'gh[pousr]_[A-Za-z0-9]{20,}'
scan "private key block"     'BEGIN [A-Z ]*PRIVATE KEY'
scan "slack token"           'xox[abprs]-[A-Za-z0-9-]{10,}'
scan "generic assignment"    '(api[_-]?key|secret|passwd|password|token)[[:space:]]*[:=][[:space:]]*["'"'"'][^"'"'"']{12,}'
# Any routable IPv4 literal. Deliberately NOT the production address itself:
# a scanner that contains the string it scans for publishes that string to
# everyone who reads the scanner, which is the whole point of the file being
# public. Matching the shape catches the current host and every future one,
# and leaks nothing. Documentation, private, loopback and link-local ranges
# are excluded because those are safe to write down on purpose.
# Any routable IPv4 literal in the tree.
#
# Deliberately NOT a match on the production address itself. A scanner that
# contains the string it is scanning for publishes that string to everyone who
# reads the scanner, and this file is meant to be public. Matching the SHAPE
# catches the current host and every future one and leaks nothing.
#
# Two stages, because ERE has no negative lookahead: pull every IPv4 literal out
# with -o, then drop the ranges that are safe to write down on purpose -- RFC
# 5737 documentation, RFC 1918 private, loopback, link-local and broadcast.
ran=$((ran + 1))
ip_raw=$(git ls-files -z | xargs -0 grep -noIE '([0-9]{1,3}\.){3}[0-9]{1,3}' 2>/dev/null)
ip_rc=$?
if [ $ip_rc -eq 2 ]; then
  say "routable ip literal" "SCAN ERROR — not a pass"; fail=1
else
  ip_hits=$(printf '%s\n' "$ip_raw" | grep -v '^$' | grep -vE ':(0\.0\.0\.0|255\.255\.255\.255|127\.[0-9]+\.[0-9]+\.[0-9]+|10\.[0-9]+\.[0-9]+\.[0-9]+|192\.168\.[0-9]+\.[0-9]+|169\.254\.[0-9]+\.[0-9]+|192\.0\.2\.[0-9]+|198\.51\.100\.[0-9]+|203\.0\.113\.[0-9]+|172\.(1[6-9]|2[0-9]|3[01])\.[0-9]+\.[0-9]+)$' || true)
  if [ -n "$ip_hits" ]; then
    say "routable ip literal" "FOUND:"; printf '%s\n' "$ip_hits" | sed 's/^/    /'; fail=1
  else
    say "routable ip literal" "pass"
  fi
fi

ran=$((ran + 1))
if git ls-files | grep -qE '(^|/)\.env($|\.)' ; then
  say "no .env tracked" "FOUND"; fail=1
else
  say "no .env tracked" "pass"
fi

echo
echo "── authorship ──"
ran=$((ran + 1))
unpushed=$(git log --format='%H' @{upstream}..HEAD 2>/dev/null || git log --format='%H' -10)
bad=0
for sha in $unpushed; do
  if git log -1 --format='%an <%ae>%n%B' "$sha" | grep -qiE 'co-authored|generated with|generated by|assisted by|claude|anthropic|copilot'; then
    say "commit ${sha:0:8}" "ATTRIBUTION FOUND"; bad=1
  fi
done
[ $bad -eq 0 ] && say "unpushed commit messages" "pass" || fail=1

echo
echo "── tree ──"
ran=$((ran + 1))
if [ -n "$(git status --porcelain)" ]; then
  say "working tree clean" "DIRTY — commit or stash first"
  git status --short | sed 's/^/    /'
  fail=1
else
  say "working tree clean" "pass"
fi

echo
echo "──────────────────────────────────────"
echo "checks run: $ran"
if [ $fail -eq 0 ]; then
  echo "PREFLIGHT PASS — every check executed and passed"
else
  echo "PREFLIGHT FAIL — do not push"
  exit 1
fi
